### ISSUE TITLE
Different listing style for main category and sub category?

### ISSUE THREAD

**Issue by r4dh4l** [jsnjack/kraiklyn#10] opened 2018-11-17 12:51 UTC
Hi @jsnjack,

I really like you "kraiklyn" theme, thank you for sharing it!

Just one thing is a little bit disturbing for me and I don't know if this is really an "issue" but anyway: When I add for example `content/contact/email.md` both "contact" and "email" is listed as

```
| Contact
| Email
```

Wouldn't it be better to seaparate the listing style a little bit, for example:

```
| Contact
\ Email
```

(or listing "Email" a little bit smaller than "Contact")?

**Comment by jsnjack** [comment] 2018-11-19 18:02
Hi!

Interesting, have you seen https://github.com/jsnjack/kraiklyn/tree/master/exampleSite/content/characters ? I think your example is the same as Characters / Balveda and this sctructure is displayed properly (https://themes.gohugo.io/theme/kraiklyn/#characters)

**Comment by r4dh4l** [comment] 2018-11-21 21:20
Hi,

thank you for your reply!

No I didn't. I'm quite new to HUGO. Do I have to activate the other fonts first to try it?

**Comment by jsnjack** [comment] 2018-11-22 11:03
The other fonts? I'm not sure what you mean... If you want to preview the example site, run something like:
```
cd exampleSite && hugo serve --theme kraiklyn --themesDir ../../ --baseURL http://localhost/
```

**Comment by r4dh4l** [comment] 2018-11-22 21:53
> The other fonts? I'm not sure what you mean...

I thought your first answer was abaout using a different font type, sry.

Let me try to show how https://themes.gohugo.io/theme/kraiklyn/#characters looks for me:

![screenshot_2018-11-22_22-50-07](https://user-images.githubusercontent.com/44623983/48922720-0248a880-eea9-11e8-8ee3-bd2f192540a6.png)

The headlines "Characters". "Bora" and "Balveda" look the same "level". If this is intended it is a little bit confusing orientate on the right pane of the website because "Bora" and "Balveda" should be sub-ordinated under "Characters" like

# Characters
## Bora
## Balveda

and not 

# Characters
# Bora
# Balveda

shoudn't it?

**Comment by jsnjack** [comment] 2018-11-22 22:11
Ah I see! It is actually intended by design. :/ I think extra space on the left is enough. However, you can always add your own styles and make it look as you want :)
Closing the issue

**Closed by jsnjack** 2018-11-22 22:11 UTC

**Comment by r4dh4l** [comment] 2019-01-13 22:37
Sorry or bothering again but may I ask where the style of how `| Bora` and `| Balveda` in the screenshot on right pane is defined?
